--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/libform
branches:
- master
projects:
  libform:
    path: ""
    type: library
    model: virion
  libform-sample:
    path: "/sample"
...
